### ISSUE TITLE
Failed to use pdumper together with native-comp

### ISSUE THREAD

**Issue by yqu212** [leezu/dotfiles#1]
When I use them together under spacemacs develop branch, I get the message "Trying to load incoherent dumped eln file:lisp-mode". Do you have any idea?

**Comment by leezu** [comment]
I haven't tried the portable dumper feature yet after switching to native-comp. I suggest you reproduce it without spacemacs (eg. something along the lines of `emacs --batch -Q -eval (dump-emacs-portable "~/emacs.pdmp")`). If you can reproduce it, the next step is to send an email to bug-gnu-emacs@gnu.org to report the bug.

**Comment by yqu212** [comment]
Thank you.

**Comment by leezu** [comment]
Thanks for reporting the bug upstream https://debbugs.gnu.org/cgi/bugreport.cgi?bug=45103
